### PR TITLE
feat: add slovak and czech languages

### PR DESCRIPTION
**Pull request by Grolicek**
I added some translations, so this can possibly work with other languages. Hope I didn't forget to add anything...

### CODE REVIEW

**Comment by lbenie** [comment]
@all-contributors please add @Grolicek for code

**Comment by lbenie** [comment]
Hey man, you'll need to rebase and squash those commits so that the commitlint message passes

i.e

`feat: add slovak and czech languages`

**Comment by Grolicek** [comment]
I think I've done it. Tell me if it's alright...

**Comment by lbenie** [comment]
Seems like the tests broke

You can run them locally with

```sh
yarn test:vitest
```

**Comment by DaDlugosch** [comment]
Any update about this contribution?

**Comment by lbenie** [comment]
> Any update about this contribution?

@Grolicek can you fix the unit tests so I can merge this?

**Comment by Grolicek** [comment]
I created a new pull request #1416 .

**Pull request closed without merging**
